const BASE_URL = 'https://www.acorntools.net';

const ROUTES = [
  {
    path: '/resize-image',
    toolId: 'resize',
    icon: '⤡',
    label: 'Resize Images',
    title: 'Resize Images Online Free — Acorn Tools',
    description: 'Resize images to exact dimensions or presets. 100% private — your files never leave your device. Supports JPEG, PNG, WebP, AVIF.',
    h1: 'Resize Images Online — Free & Private',
    seoContent: 'Scale images to exact pixel dimensions, percentages, or common presets. All processing happens in your browser — nothing is uploaded to any server. Supports JPEG, PNG, WebP, and AVIF formats.',
  },
  {
    path: '/compress-image',
    toolId: 'compress',
    icon: '▼',
    label: 'Compress Images',
    title: 'Compress Images Online Free — Acorn Tools',
    description: 'Reduce image file size with quality control. 100% private — your files never leave your device. Supports JPEG, PNG, WebP.',
    h1: 'Compress Images Online — Free & Private',
    seoContent: 'Reduce image file sizes with adjustable quality control. See before/after comparisons in real time. All compression happens locally in your browser — your images are never uploaded anywhere.',
  },
  {
    path: '/convert-image',
    toolId: 'convert',
    icon: '⇄',
    label: 'Convert Image Format',
    title: 'Convert Image Format Online Free — Acorn Tools',
    description: 'Convert between PNG, JPG, WebP, AVIF and more. 100% private — your files never leave your device.',
    h1: 'Convert Image Format — Free & Private',
    seoContent: 'Convert images between formats: PNG to JPG, WebP to PNG, AVIF to JPEG, and more. All conversion happens in your browser — no upload, no server, no tracking.',
  },
  {
    path: '/crop-image',
    toolId: 'crop',
    icon: '⬒',
    label: 'Crop Images',
    title: 'Crop Images Online Free — Acorn Tools',
    description: 'Crop images by selecting a region. 100% private — your files never leave your device.',
    h1: 'Crop Images Online — Free & Private',
    seoContent: 'Select and export a region of any image. Drag to crop with pixel-perfect precision. All processing runs locally in your browser — your files stay on your device.',
  },
  {
    path: '/strip-metadata',
    toolId: 'metadata',
    icon: '⊘',
    label: 'Strip Metadata',
    title: 'Strip EXIF Metadata from Images & PDFs — Acorn Tools',
    description: 'Remove GPS location, device info, timestamps, and other metadata from images and PDFs. 100% private — nothing is uploaded.',
    h1: 'Strip Metadata from Images & PDFs — Free & Private',
    seoContent: 'Remove EXIF data, GPS coordinates, camera info, timestamps, and other hidden metadata from your images and PDFs. Essential for privacy before sharing files. All processing happens on your device.',
  },
  {
    path: '/image-to-pdf',
    toolId: 'img2pdf',
    icon: '▤',
    label: 'Image to PDF',
    title: 'Convert Images to PDF Online Free — Acorn Tools',
    description: 'Combine images into a single PDF document. 100% private — your files never leave your device.',
    h1: 'Convert Images to PDF — Free & Private',
    seoContent: 'Combine multiple images into a single PDF document. Drag to reorder, adjust page sizes, and export instantly. Everything runs in your browser — no upload needed.',
  },
  {
    path: '/pdf-to-image',
    toolId: 'pdf2img',
    icon: '▥',
    label: 'PDF to Image',
    title: 'Convert PDF to Image Online Free — Acorn Tools',
    description: 'Convert PDF pages to high-quality JPEG or PNG images. 100% private — your files never leave your device.',
    h1: 'Convert PDF to Image — Free & Private',
    seoContent: 'Convert PDF pages to high-quality JPEG or PNG images. Choose resolution and format. All conversion happens locally — your PDFs never leave your device.',
  },
  {
    path: '/compress-pdf',
    toolId: 'pdfcompress',
    icon: '▼',
    label: 'Compress PDF',
    title: 'Compress PDF Online Free — Acorn Tools',
    description: 'Reduce PDF file size while preserving quality. Smart compression keeps text sharp. 100% private — nothing is uploaded.',
    h1: 'Compress PDF Online — Free & Private',
    seoContent: 'Reduce PDF file size with smart or aggressive compression. Smart mode preserves text and vectors while optimizing embedded images. Your PDFs are never uploaded — all processing runs locally.',
    defaultMode: 'compress',
  },
  {
    path: '/pdf-toolkit',
    toolId: 'pdftools',
    icon: '⊞',
    label: 'PDF Toolkit',
    title: 'PDF Toolkit — Merge, Split, Rotate, Watermark — Acorn Tools',
    description: 'All-in-one PDF toolkit: merge, split, rotate, watermark, add page numbers. 100% private — nothing is uploaded.',
    h1: 'PDF Toolkit — Free & Private',
    seoContent: 'A complete PDF toolkit: merge multiple files, split by page range, rotate pages, add watermarks, and insert page numbers. All processing runs locally in your browser — your documents never leave your device.',
  },
  {
    path: '/merge-pdf',
    toolId: 'pdftools',
    icon: '⊞',
    label: 'Merge PDFs',
    title: 'Merge PDF Files Online Free — Acorn Tools',
    description: 'Combine multiple PDF files into one document. Drag to reorder. 100% private — nothing is uploaded.',
    h1: 'Merge PDF Files — Free & Private',
    seoContent: 'Combine multiple PDF files into a single document. Drag and drop to reorder pages. All merging happens in your browser — your documents are never uploaded to any server.',
    defaultMode: 'merge',
  },
  {
    path: '/split-pdf',
    toolId: 'pdftools',
    icon: '⊞',
    label: 'Split PDF',
    title: 'Split PDF Online Free — Acorn Tools',
    description: 'Split a PDF into multiple files by page range. 100% private — nothing is uploaded.',
    h1: 'Split PDF — Free & Private',
    seoContent: 'Split PDF documents into separate files by page range. Extract individual pages or groups. All processing happens in your browser — your files stay on your device.',
    defaultMode: 'split',
  },
  {
    path: '/rotate-pdf',
    toolId: 'pdftools',
    icon: '⊞',
    label: 'Rotate PDF',
    title: 'Rotate PDF Pages Online Free — Acorn Tools',
    description: 'Rotate PDF pages 90°, 180°, or 270°. Fix upside-down scans. 100% private — nothing is uploaded.',
    h1: 'Rotate PDF Pages — Free & Private',
    seoContent: 'Rotate individual PDF pages or all pages at once. Fix landscape/portrait orientation or upside-down scans. All processing happens in your browser — your documents never leave your device.',
    defaultMode: 'rotate',
  },
  {
    path: '/watermark-pdf',
    toolId: 'pdftools',
    icon: '⊞',
    label: 'Watermark PDF',
    title: 'Add Watermark to PDF Online Free — Acorn Tools',
    description: 'Add text watermarks to PDF documents. Customize opacity, size, and position. 100% private — nothing is uploaded.',
    h1: 'Add Watermark to PDF — Free & Private',
    seoContent: 'Add custom text watermarks to your PDF documents. Control opacity, font size, rotation, and color. All processing runs locally in your browser — your files are never uploaded.',
    defaultMode: 'watermark',
  },
  {
    path: '/pdf-page-numbers',
    toolId: 'pdftools',
    icon: '⊞',
    label: 'Add Page Numbers to PDF',
    title: 'Add Page Numbers to PDF Online Free — Acorn Tools',
    description: 'Add page numbers to PDF documents. Choose position and format. 100% private — nothing is uploaded.',
    h1: 'Add Page Numbers to PDF — Free & Private',
    seoContent: 'Add page numbers to your PDF documents with customizable position, format, and starting number. Everything runs in your browser — your PDFs never leave your device.',
    defaultMode: 'pagenums',
  },
  {
    path: '/redact-pdf',
    toolId: 'pdfredact',
    icon: '█',
    label: 'Redact PDF',
    title: 'Redact PDF Online Free — Acorn Tools',
    description: 'Permanently redact sensitive content from PDFs. Draw over text, images, or any area to remove it. 100% private — nothing is uploaded.',
    h1: 'Redact PDF — Free & Private',
    seoContent: 'Permanently remove sensitive information from PDF documents. Draw rectangles over text, images, or any content to redact it. True redaction — the original content is destroyed, not just covered. All processing runs locally in your browser.',
  },
  {
    path: '/pdf-pages',
    toolId: 'pdforganize',
    icon: '⊞',
    label: 'Organize PDF Pages',
    title: 'Reorder & Delete PDF Pages Online Free — Acorn Tools',
    description: 'Reorder, delete, and insert PDF pages with drag-and-drop. 100% private — nothing is uploaded.',
    h1: 'Organize PDF Pages — Free & Private',
    seoContent: 'Reorder, delete, and insert pages in your PDF documents. Visual drag-and-drop interface with page thumbnails. Everything runs locally — your PDFs never leave your device.',
  },
];

// Build lookup maps
export const ROUTE_BY_PATH = Object.fromEntries(ROUTES.map(r => [r.path, r]));
export const ROUTE_BY_TOOL_ID = {};
for (const r of ROUTES) {
  // First route per toolId wins (used for home page links)
  if (!ROUTE_BY_TOOL_ID[r.toolId]) ROUTE_BY_TOOL_ID[r.toolId] = r;
}

export { ROUTES, BASE_URL };
